
server:
  port: 7777
spring:
  application:
    name: eureka-gateway
  cloud:
    gateway:
      routes:
      - id: blog-mian-service
        uri: lb://blog-main-service
        predicates:
        - Path=/blog/**
      - id: baidu
        uri: http://top.baidu.com
        predicates:
        - Path=/board/**
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
  config: classpath:logback.xml